name: test-stackignore-template
description: This is a stack for testing stackignore
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  - name: input_field
    description: text input field
    required: true

configs:
 environments: 
    - name: staging
      parameters: 
        protected-branches: false
